//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportResources
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirConnection", Namespace="http://schemas.datacontract.org/2004/07/AirportResources")]
    public partial class AirConnection : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AirportAField;
        
        private string AirportBField;
        
        private System.DateTime ArrivalTimeField;
        
        private System.DateTime DepartureTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AirportA
        {
            get
            {
                return this.AirportAField;
            }
            set
            {
                this.AirportAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AirportB
        {
            get
            {
                return this.AirportBField;
            }
            set
            {
                this.AirportBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArrivalTime
        {
            get
            {
                return this.ArrivalTimeField;
            }
            set
            {
                this.ArrivalTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureTime
        {
            get
            {
                return this.DepartureTimeField;
            }
            set
            {
                this.DepartureTimeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAirportService")]
public interface IAirportService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportService/GetAllAirConnections", ReplyAction="http://tempuri.org/IAirportService/GetAllAirConnectionsResponse")]
    AirportResources.AirConnection[] GetAllAirConnections(string portA, string portB);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportService/GetAllAirConnections", ReplyAction="http://tempuri.org/IAirportService/GetAllAirConnectionsResponse")]
    System.Threading.Tasks.Task<AirportResources.AirConnection[]> GetAllAirConnectionsAsync(string portA, string portB);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportService/GetAirConnections", ReplyAction="http://tempuri.org/IAirportService/GetAirConnectionsResponse")]
    AirportResources.AirConnection[] GetAirConnections(string portA, string portB, System.DateTime from, System.DateTime to);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAirportService/GetAirConnections", ReplyAction="http://tempuri.org/IAirportService/GetAirConnectionsResponse")]
    System.Threading.Tasks.Task<AirportResources.AirConnection[]> GetAirConnectionsAsync(string portA, string portB, System.DateTime from, System.DateTime to);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAirportServiceChannel : IAirportService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AirportServiceClient : System.ServiceModel.ClientBase<IAirportService>, IAirportService
{
    
    public AirportServiceClient()
    {
    }
    
    public AirportServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AirportServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AirportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AirportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public AirportResources.AirConnection[] GetAllAirConnections(string portA, string portB)
    {
        return base.Channel.GetAllAirConnections(portA, portB);
    }
    
    public System.Threading.Tasks.Task<AirportResources.AirConnection[]> GetAllAirConnectionsAsync(string portA, string portB)
    {
        return base.Channel.GetAllAirConnectionsAsync(portA, portB);
    }
    
    public AirportResources.AirConnection[] GetAirConnections(string portA, string portB, System.DateTime from, System.DateTime to)
    {
        return base.Channel.GetAirConnections(portA, portB, from, to);
    }
    
    public System.Threading.Tasks.Task<AirportResources.AirConnection[]> GetAirConnectionsAsync(string portA, string portB, System.DateTime from, System.DateTime to)
    {
        return base.Channel.GetAirConnectionsAsync(portA, portB, from, to);
    }
}
